abstract: "[One line description of module's purpose here]"
author: Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.59
license: perl
name: Class-Accessor-Named
no_index: 
  directory: 
    - inc
    - t
requires: 
  Test::More: 0
version: 0.001
