abstract: Better profiling output for Class::Accessor
author: Jesse Vincent <jesse@bestpractical.com>
build_requires: 
  Test::Dependencies: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Class-Accessor-Named
no_index: 
  directory: 
    - inc
    - t
requires: 
  Hook::LexWrap: 0
  Sub::Name: 0
  UNIVERSAL::require: 0
version: 0.002
