abstract: Better profiling output for Class::Accessor
author: Jesse Vincent <jesse@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Class-Accessor-Named
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0
  Hook::LexWrap: 0
  Sub::Name: 0
  UNIVERSAL::require: 0
version: 0.008
